name: ML Workflow

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python Environment
        run: |
          python3 -m pip install --upgrade pip
          python3 -m venv .venv
          . .venv/bin/activate
          ./venv/bin/pip install -r requirements.txt

      - name: Train and eval
        run: |
          . .venv/bin/activate
          ./venv/bin/jupyter execute notebook.ipynb
