name: ML Workflow

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python Environment
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Train and eval
        run: |
          jupyter execute notebook.ipynb
